default: &default
  adapter: postgresql
  encoding: unicode
  username: pantaukorupsi
  password: pantaukorupsi
  host: 127.0.0.1
  pool: 5

development:
  <<: *default
  database: PantauKorupsi_development

test:
  <<: *default
  database: PantauKorupsi_test

production:
  <<: *default
  database: PantauKorupsi_production
  username: pantaukorupsi
  password: <%= ENV['DATABASE_PASSWORD'] %>